home: "http://www.railstutorial.org"
help: "http://www.railstutorial.org/help"
book: "http://www.railstutorial.org/book"
rails: "http://rubyonrails.org"
screen: "http://screencasts.railstutorial.org"
contact: "http://www.railstutorial.org/contact"
news: "http://news.railstutorial.org"
valid_name: 50
valid_email: 255
valid_password: 6
